/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NoteImport } from './routes/note'
import { Route as MonthImport } from './routes/month'
import { Route as CalendarImport } from './routes/calendar'
import { Route as IndexImport } from './routes/index'
import { Route as JamsIndexImport } from './routes/jams/index'
import { Route as JamsJamImport } from './routes/jams/$jam'

// Create/Update Routes

const NoteRoute = NoteImport.update({
  id: '/note',
  path: '/note',
  getParentRoute: () => rootRoute,
} as any)

const MonthRoute = MonthImport.update({
  id: '/month',
  path: '/month',
  getParentRoute: () => rootRoute,
} as any)

const CalendarRoute = CalendarImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const JamsIndexRoute = JamsIndexImport.update({
  id: '/jams/',
  path: '/jams/',
  getParentRoute: () => rootRoute,
} as any)

const JamsJamRoute = JamsJamImport.update({
  id: '/jams/$jam',
  path: '/jams/$jam',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarImport
      parentRoute: typeof rootRoute
    }
    '/month': {
      id: '/month'
      path: '/month'
      fullPath: '/month'
      preLoaderRoute: typeof MonthImport
      parentRoute: typeof rootRoute
    }
    '/note': {
      id: '/note'
      path: '/note'
      fullPath: '/note'
      preLoaderRoute: typeof NoteImport
      parentRoute: typeof rootRoute
    }
    '/jams/$jam': {
      id: '/jams/$jam'
      path: '/jams/$jam'
      fullPath: '/jams/$jam'
      preLoaderRoute: typeof JamsJamImport
      parentRoute: typeof rootRoute
    }
    '/jams/': {
      id: '/jams/'
      path: '/jams'
      fullPath: '/jams'
      preLoaderRoute: typeof JamsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/month': typeof MonthRoute
  '/note': typeof NoteRoute
  '/jams/$jam': typeof JamsJamRoute
  '/jams': typeof JamsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/month': typeof MonthRoute
  '/note': typeof NoteRoute
  '/jams/$jam': typeof JamsJamRoute
  '/jams': typeof JamsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/month': typeof MonthRoute
  '/note': typeof NoteRoute
  '/jams/$jam': typeof JamsJamRoute
  '/jams/': typeof JamsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar' | '/month' | '/note' | '/jams/$jam' | '/jams'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar' | '/month' | '/note' | '/jams/$jam' | '/jams'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/month'
    | '/note'
    | '/jams/$jam'
    | '/jams/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  MonthRoute: typeof MonthRoute
  NoteRoute: typeof NoteRoute
  JamsJamRoute: typeof JamsJamRoute
  JamsIndexRoute: typeof JamsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  MonthRoute: MonthRoute,
  NoteRoute: NoteRoute,
  JamsJamRoute: JamsJamRoute,
  JamsIndexRoute: JamsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/calendar",
        "/month",
        "/note",
        "/jams/$jam",
        "/jams/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/calendar": {
      "filePath": "calendar.tsx"
    },
    "/month": {
      "filePath": "month.tsx"
    },
    "/note": {
      "filePath": "note.tsx"
    },
    "/jams/$jam": {
      "filePath": "jams/$jam.tsx"
    },
    "/jams/": {
      "filePath": "jams/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
